### ISSUE TITLE
Nested structure bug on windows

### ISSUE THREAD

**Issue by jbaf** [blitzrk/sublime_libsass#16]
Hello ! You thought you could get rid of me so easyly ? Think again.
In fact this time, the bug didn't happened to me, but to one of my colleagues on windows.

Here is the conf file of our project : 

```
"output": {
        "dir": "frontoffice/ressources/css",      // Relative or absolute path (can have ..)
        "structure": ["nested", "frontoffice/ressources/scss"]       // "flat", "nested", or ["nested", "relative/root/of/nest"]
    },
"compile": {
        "style": "expanded",             // String | Output style: nested/expanded/compact/compressed
        "line-numbers": false,      // Bool   | Emit comments showing original line numbers
        "line-comments": false,     // Bool   | Alias for line-numbers, does not override
        "load-path": false,         // List   | Sass import paths: e.g. [ "C:\bourbon", "C:\compass" ]
        "plugin-path": false,       // String | Path to autoload plugins (libsass issue 878)
        "sourcemap": true,         // Bool   | Emit .css.map file for debugging in browser
        "omit-map-comment": false,  // Bool   | Omit comment about .css.map file in .css file
        "precision": false          // Int    | Decimal places for computed values
}
```

On my Mac, your plugin works great with that conf, but on his windows 10 (yaiks !), the nesting structure isn't respected.
Instead of replicating the file structure from `frontoffice/ressources/scss` to `frontoffice/ressources/css`, it actualy recreates the whole structure from the root f the project to `frontoffice/ressources/css`, compiling the scss in `frontoffice/ressources/css/frontoffice/ressources/css`

Any Idea where this bug can come from ?

**Comment by blitzrk** [comment]
Hey, good to have you back!

Um, yeah. There are a few places. I'll fire up a VM and see what I can find.

**Comment by blitzrk** [comment]
Let me know if 0.9.7 fixes it for you. I'll be testing it out myself in a little bit.

**Comment by blitzrk** [comment]
With some limited testing, it looks like it's working now. I'll wait for your confirmation or further testing, though.

**Comment by jbaf** [comment]
Great ! According to my colleague, it works well.
Thank you very much.
