### ISSUE TITLE
Building partials in a subfolder seems to do nothing

### ISSUE THREAD

**Issue by jbaf** [blitzrk/sublime_libsass#9]
Hello, It's me again (you'll never get rid of me... unless you do ^^).

Well, I successfully updated to 0.9.0, and the nested compile works great.
Unfortunately, I still have my other problem : compiling from partials that are stored in a subfolder is still doing nothing... And no error showing in the console.
That's pretty weird.

To see if my file structure was involved in that error, I made a test with the sass version of Font Awesome. I hosted the files I used for testing on weTransfer : http://we.tl/tEIMVJnCRl

And nested it like this on mac, in local storage (but the same happened on windows with files hosted on a NAS) : 

```
|-- dev/
|   |
|   |-- scss/
|   |   +-- font-awesome.scss
|   |   |-- font-awesome/
|   |   |   +-- _partials.scss
|   |
|   |-- css/
|   |   +-- font-awesome.css
|   |
|-- .libsass.json

```

I did that simple thing : addig a `/* Do work */`comment on top of the file and looking at the output css file. Inserting that comment in `font-awesome.scss` worked great. Inserting it on top of `font-awesome/_variables.scss` and trying to compile **from that file** didn't do anything.

That's really weird.

Thanks again for your implication in this.

**Comment by blitzrk** [comment]
I knew this would either be really easy (typo) or really hard (problem with python or unicode). Luckily it's the former. This is just an issue of single and double-quotes in the import statements. Fix will be up as soon as possible.

**Comment by blitzrk** [comment]
Thanks for sticking through this with me!

**Comment by jbaf** [comment]
Cool ! I hope this is it. Thank you.
Again, it's my pleasure to contribute to your promising plugin.

**Comment by blitzrk** [comment]
Hopefully from here on out it's more features and fewer bugs. Let me know if there's anything that would make this plugin better for you. :)

**Comment by jbaf** [comment]
Sure will. Let me know when your new update is available.

**Comment by blitzrk** [comment]
I'll post here. Bad sign, though. It looks like PackageControl's servers may have been down for the past 17 hours. It won't update until they're fixed and discover my update...

**Comment by jbaf** [comment]
Damn... I can't find your update in PC, 2 days later. Is it still a PC server related problem ?
I can't wait to test this new version.

**Comment by blitzrk** [comment]
Yeah, it is... Maybe @wbond is having a Github API key problem? I'm not sure how to best contact him.

You could try it by adding `"repositories": ["https://github.com/blitzrk/sublime_libsass.git"]` to `Preferences > Package Settings > Package Control > Settings – User` and then removing it when PC gets updated.

**Comment by jbaf** [comment]
This is really weird... Seems that PC hasn't updated the list yet. I still see v0.9.0 in it.
And I'm not sure if adding the github repo manually did something at all, because when I install from this repo, the result is exactly the same... I think i'll just wait untill the Package Control issue is fixed. then I will be sure I have the right version.
Keep me posted if you have some news in that regard. thanks ;)

**Comment by blitzrk** [comment]
Talked to wbond today. He found the issue and fixed it. Now it's updated, so let me know if it works tomorrow!

**Comment by jbaf** [comment]
Well, here is some improvement : when I test it on some other projetcs than mine (such as Font awesome, for instance), it works perfectly.
But unfortunately, there is still a bug on my own project boilerplate... but not the same as before, and a very weird one !

I created a blank partial file in the `scss/base` directory and @imported it at the top of `main.scss`. Then I tried to put a `/**/` comment in it to see if it appears weel in my output file.
As long as this file is imported at the beginning of `main.scss`, the changes apprear in`main.css`. But as soon as I import it after another partial (in this case, that is "`base/reset.scss`"), sublime pukes on me and displays "error' at the left of the footer bar, but no error in the console.
Even weirder, I noticed that, whatever the file I try to compile from, the line and colum of the error are always the ones where my cursor is at the moment.

I e-mailed you my files on your gmail adress so you can test it and see for yourself.

I really hope you will find what causes this. This is getting close to perfection, and I long for the moment it will finally work for me.

Thank you.

**Comment by blitzrk** [comment]
Just tested it. When I added `@import 'base/reset';` before `base/test`, I got `Error: no mixin named box-sizing` in the ctrl+` window. So I just imported (again) `outils/mixin-tools` before it (where the box-sizing mixin was) and it worked.

If that's the issue, we'll have to figure out why the error didn't display for you. What's your Sublime version again?

**Comment by jbaf** [comment]
Even though, that's a weird error, as `outils/mixin-tools` is like the second partial included in main.scss, and it is included way before `base/reset`. Anyway, maybe my SCSS contains something anywhere else that sould be an error and as you pointed it, I have no error log in my console, so I can't tell.

Quick question, btw : the ctrl+` window you mention is the sublime text console, right ? Because I work on a french mac keyboard (pretty fucked up) and the shortcut never worked for me for some unknown reason. So I open the console by the menu view/show console. Is that right ? Just checking that I look in the right place.
FWI I work in sublime text 3 (build 3103, the latest release) on mac OS 10.11.3.

**Comment by blitzrk** [comment]
Oh, I've heard terrible things about french keyboards. It looks like the backtick is very hidden. http://superuser.com/questions/254076/how-do-i-type-the-tick-and-backtick-characters-on-windows But yeah, it's the same as `View`->`Show Console`.

I was trying to follow your steps exactly, so I started by putting `@import 'base/test';` at the very top of `main.scss`. That worked, so then I put `@import 'base/reset';` above it. That's when it failed with error message. At this point, reset is first and mixin-tools is 4th, so I had to move mixin-tools up to the top to get it to compile.

So I **think** this isn't a new bug in the build system, but I'll test on a Mac when I get a chance to see if something's going on with error messages not being displayed. It's working as expected on Linux with the same ST3 version.

So close!

**Comment by jbaf** [comment]
In fact, in my testing process, I didn't move `base/reset` on top. It stayed where it was.
The only file I tried to move was `base/test`. 
On top of the document, it worked. But wherever I moved it, even right after the first @include `outils/functions` (so the order of the rest stays the same), it displayed an error in the footer bar, and absolutely none in the console, as I explained.

**Comment by blitzrk** [comment]
Sorry, I misread. I can't reproduce the problem. Let's continue searching for the cause over email.

Oh, and the line and column number of your cursor are just something that Sublime displays by default. If there was an error compiling it would show `Error: file.scss` to the left of the line and column for 5 seconds.

**Comment by jbaf** [comment]
That's precisely what it displays : `Error : _test.scss line x column x`.

**Comment by jbaf** [comment]
Damn... I think I found what causes my bug and it's pretty fucked up.
Sit down, please. Oh you already sit. Good. Are you ready ?

I only removed the indentation of my @import rules in `main.scss` and now it works... Indentation !!
All this for that. I can go kill myself in peace now.

Ok I may be overreacting... Maybe you should look into it though. I don't know if it is mac related, but t's a pretty weird issue, don't you think ?
So now that it works, I'll test your plugin this morning and see if other bug occur.

Thanks again for your precious help.

**Comment by blitzrk** [comment]
Oh man! That is ridiculous. You know, yesterday that was actually one of my tests. I made the indentation all jagged to try to trip it up. 

Ugh, these insidious little problems. Very very weird. My method should completely ignore spaces and tabs, but it's not acting like a problem with the sass compiler. 

I'm gonna do everything to find the cause of this problem. Any chance you can email me which other plugins you have installed? 

Thank you so much for not giving up on my plugin!

**Comment by jbaf** [comment]
You've got it in your mail box.
I tested your plugin all morning and now that I modified that freakin' indentation it works great. The error log is working as well, but I didn't test @error and @warn rules in it.
Long story short : everything is fine, now.
